---
filebeat.prospectors:
- input_type: log
  paths:
  - /payload/software/log/*.json
  json.keys_under_root: true
  json.add_error_key: true
  tags:
  - json
      
output.elasticsearch:
  hosts: ["http://${ES_DNS}:9200"]
  index: "import-logs"

